### ISSUE TITLE
Unable to download the file

### ISSUE THREAD

**Issue by macmatrix** [tomwyr/avataaar-image#11] opened 2020-05-12 12:39 UTC
I am not able to download the file with the .random() function. I am ok to download file if I set the attribute manually.

Here is the error

> flutter: CacheManager: Failed to download file from https://avataaars.io/png/128.0?topType=LongHairMiaWallace&accessoriesType=Prescription02&hairColor=PastelPink&clotheType=ShirtVNeck&clotheColor=PastelGreen&eyeType=Default&eyebrowType=Angry&mouthType=Eating&skinColor=Brown with error:
> HttpException: Invalid statusCode: 503, uri = https://avataaars.io/png/128.0?topType=LongHairMiaWallace&accessoriesType=Prescription02&hairColor=PastelPink&clotheType=ShirtVNeck&clotheColor=PastelGreen&eyeType=Default&eyebrowType=Angry&mouthType=Eating&skinColor=Brown

**Comment by tomwyr** [comment] 2020-05-12 13:07
I'm pretty sure this is some Avataaars API issue. I was unable to open avatar via the link you provided but I tried again after several minutes and everything seems to work fine.

Let me know if the issue won't disappear in your case.

**Comment by macmatrix** [comment] 2020-05-12 13:45
thanks for the quick response. Do you know how frequently is this happening? I was thinking to use your plugin for a production app but if the service is not consistent I will need to look somewhere else 
many thanks for the job you did!

**Comment by tomwyr** [comment] 2020-05-12 14:08
I've been using it a bit in the past and this is the first time I see an issue like this one. But yeah, it's an open source project and outages like this one could happen time to time.

**Comment by tomwyr** [comment] 2020-05-19 20:03
Closing the issue as it was most probably caused by temporary outage of avatars service.

**Closed by tomwyr** 2020-05-19 20:03 UTC
